/*
 * Author: Eric Bruneton
 * Modified and ported to Unity by Justin Hawkins 2014
 * Modified by Denis Ovchinnikov 2015-2016
 */
 
#pragma kernel CSMain
#define NUM_THREADS 8

float k;

Texture2D<float4> deltaERead;
Texture2D<float4> irradianceRead;

RWTexture2D<float4> irradianceWrite;

[numthreads(NUM_THREADS, NUM_THREADS, 1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	// k=0 for line 4, k=1 for line 10
	irradianceWrite[id.xy] = irradianceRead[id.xy] + k * deltaERead[id.xy];  
}