#pragma kernel RGBA2AAAA

Texture2D<float4> Input0;
RWTexture2D<float> Output0;

[numthreads(32, 32, 1)]
void RGBA2AAAA(uint3 id : SV_DispatchThreadID)
{
	float a = Input0[id.xy].a;

	Output0[id.xy] = a;
}

#pragma kernel RGBA2RGB1

Texture2D<float4> Input1;
RWTexture2D<float4> Output1;

[numthreads(32, 32, 1)]
void RGBA2RGB1(uint3 id : SV_DispatchThreadID)
{
	float3 c = Input1[id.xy].rgb;

	Output1[id.xy] = float4(c, 1.0);
}